[workspace]
resolver = "3"
members = ["fjord", "shell"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "LicenseRef-NorOS-Proprietary"

[workspace.dependencies]
# Pinned to the exact revision Fjord was written against.
smithay = { git = "https://github.com/Smithay/smithay", rev = "118e34ffc9b99854a2230c4805e1f37dc9029edb", default-features = false }
smithay-drm-extras = { git = "https://github.com/Smithay/smithay", rev = "118e34ffc9b99854a2230c4805e1f37dc9029edb", default-features = false }

[profile.release]
lto = "thin"
codegen-units = 4
strip = true
